### ISSUE TITLE
NoSuchMethodError DateMathParser.parse

### ISSUE THREAD

**Issue by EdgeCaseBerg** [jprante/elasticsearch-knapsack#64]
Hello! I'm getting an error when attempting to export. It's not stopping the export itself, as that finishes and gives me a completed file, but it does throw an exception afterward sending back error JSON instead of the successful ones. 

This happens after a regular `curl -XPOST localhost:9200/_export/

Here's the error:

```

[2015-03-12 16:56:42,685][INFO ][KnapsackExportAction     ] end of export: {"mode":"export","started":"2015-03-12T20:56:15.494Z","path":"file:///Users/EdgeCaseBerg/tmp/all.tar.gz","node_name":"Tom Corsi"}, packets = 62724, total bytes transferred = 18553017, rate = 547028.800000
[2015-03-12 16:57:07,454][ERROR][KnapsackExportAction     ] org.elasticsearch.common.joda.DateMathParser.parse(Ljava/lang/String;J)J
java.lang.NoSuchMethodError: org.elasticsearch.common.joda.DateMathParser.parse(Ljava/lang/String;J)J
        at org.xbib.elasticsearch.knapsack.KnapsackState.fromXContent(KnapsackState.java:134)
        at org.xbib.elasticsearch.knapsack.KnapsackService.parseStates(KnapsackService.java:176)
        at org.xbib.elasticsearch.knapsack.KnapsackService.get(KnapsackService.java:119)
        at org.xbib.elasticsearch.knapsack.KnapsackService.getExports(KnapsackService.java:103)
        at org.xbib.elasticsearch.knapsack.KnapsackService.addExport(KnapsackService.java:107)
        at org.xbib.elasticsearch.action.knapsack.exp.TransportKnapsackExportAction.doExecute(TransportKnapsackExportAction.java:117)
        at org.xbib.elasticsearch.action.knapsack.exp.TransportKnapsackExportAction.doExecute(TransportKnapsackExportAction.java:65)
        at org.elasticsearch.action.support.TransportAction.execute(TransportAction.java:75)
        at org.elasticsearch.client.node.NodeIndicesAdminClient.execute(NodeIndicesAdminClient.java:77)
        at org.elasticsearch.client.FilterClient$IndicesAdmin.execute(FilterClient.java:120)
        at org.elasticsearch.rest.BaseRestHandler$HeadersAndContextCopyClient$IndicesAdmin.execute(BaseRestHandler.java:149)
        at org.xbib.elasticsearch.rest.action.knapsack.exp.RestKnapsackExportAction.handleRequest(RestKnapsackExportAction.java:78)
        at org.elasticsearch.rest.BaseRestHandler.handleRequest(BaseRestHandler.java:53)
        at org.elasticsearch.rest.RestController.executeHandler(RestController.java:197)
        at org.elasticsearch.rest.RestController.dispatchRequest(RestController.java:180)
        at org.elasticsearch.http.HttpServer.internalDispatchRequest(HttpServer.java:121)
        at org.elasticsearch.http.HttpServer$Dispatcher.dispatchRequest(HttpServer.java:83)
        at org.elasticsearch.http.netty.NettyHttpServerTransport.dispatchRequest(NettyHttpServerTransport.java:319)
        at org.elasticsearch.http.netty.HttpRequestHandler.messageReceived(HttpRequestHandler.java:61)
        at org.elasticsearch.common.netty.channel.SimpleChannelUpstreamHandler.handleUpstream(SimpleChannelUpstreamHandler.java:70)
        at org.elasticsearch.common.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564)
        at org.elasticsearch.common.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendUpstream(DefaultChannelPipeline.java:791)
        at org.elasticsearch.http.netty.pipelining.HttpPipeliningHandler.messageReceived(HttpPipeliningHandler.java:60)
        at org.elasticsearch.common.netty.channel.SimpleChannelHandler.handleUpstream(SimpleChannelHandler.java:88)
```

**Comment by jprante** [comment]
What version of Knapsack and ES do you use?

**Comment by EdgeCaseBerg** [comment]
Elastic Search Version: 1.4.4
Knapsack Version: 1.4.0.0

On Thu, Mar 12, 2015 at 02:23:23PM -0700, J�rg Prante wrote:
> What version of Knapsack and ES do you use?
> 
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/jprante/elasticsearch-knapsack/issues/64#issuecomment-78624429

-- 

~Ethan J. Eldridge
http://www.ethanjoachimeldridge.info
Programmer | Computer Scientist
Former UVM CS Crew Executive Triumvirate Member
Former UPE UVM Chapter President
PGP Key: EFFF2B10 on pgp.mit.edu

**Comment by jprante** [comment]
Thanks. Please use new version of plugin 1.4.4.0, it contains a fix.

**Comment by EdgeCaseBerg** [comment]
Thanks! 

I uninstalled the previous knapsack version and reinstall 1.4.4 and the export now works, thanks a bunch! 

```
curl -XPOST localhost:9200/megacorp/employee/_export/?path=/Users/EdgeCaseBerg/tmp/_megacorp_employee.tar.gz
{"running":true,"state":{"mode":"export","started":"2015-03-13T12:54:46.599Z","path":"file:///Users/EdgeCaseBerg/tmp/_megacorp_employee.tar.gz","node_name":"Bedlam II"}}
```
