### ISSUE TITLE
2.2.0 Support

### ISSUE THREAD

**Issue by marklit** [jprante/elasticsearch-knapsack#94]
Elasticsearch 2.2.0 is complaining Knapsack is incompatible.

From `/var/log/elasticsearch/elasticsearch.log` after starting Elasticsearch:

```
java.lang.IllegalArgumentException: Plugin [knapsack] is incompatible with Elasticsearch [2.2.0]. Was designed for version [2.1.1]
        at org.elasticsearch.plugins.PluginInfo.readFromProperties(PluginInfo.java:118)
        at org.elasticsearch.plugins.PluginsService.getPluginBundles(PluginsService.java:378)
        at org.elasticsearch.plugins.PluginsService.<init>(PluginsService.java:128)
        at org.elasticsearch.node.Node.<init>(Node.java:146)
        at org.elasticsearch.node.Node.<init>(Node.java:128)
        at org.elasticsearch.node.NodeBuilder.build(NodeBuilder.java:145)
        at org.elasticsearch.bootstrap.Bootstrap.setup(Bootstrap.java:178)
        at org.elasticsearch.bootstrap.Bootstrap.init(Bootstrap.java:285)
        at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:35)
[2016-02-05 14:40:37,814][INFO ][node                     ] [Tom Thumb] version[2.2.0], pid[18500], build[8ff36d1/2016-01-27T13:32:39Z]
[2016-02-05 14:40:37,814][INFO ][node                     ] [Tom Thumb] initializing ...
[2016-02-05 14:40:38,463][ERROR][bootstrap                ] Exception
java.lang.IllegalArgumentException: Plugin [knapsack] is incompatible with Elasticsearch [2.2.0]. Was designed for version [2.1.1]
        at org.elasticsearch.plugins.PluginInfo.readFromProperties(PluginInfo.java:118)
        at org.elasticsearch.plugins.PluginsService.getPluginBundles(PluginsService.java:378)
        at org.elasticsearch.plugins.PluginsService.<init>(PluginsService.java:128)
        at org.elasticsearch.node.Node.<init>(Node.java:146)
        at org.elasticsearch.node.Node.<init>(Node.java:128)
        at org.elasticsearch.node.NodeBuilder.build(NodeBuilder.java:145)
        at org.elasticsearch.bootstrap.Bootstrap.setup(Bootstrap.java:178)
        at org.elasticsearch.bootstrap.Bootstrap.init(Bootstrap.java:285)
        at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:35)
```

**Comment by jprante** [comment]
I have just released a version 2.2.0.0 for ES 2.2.0
